// PicoClaw Agent — type definitions
// Rule-based intent matching with json-rules-engine, no LLM required

/** Result returned by every tool executor */
export interface ToolResult {
  success: boolean;
  message: string;
  data?: unknown;
}

/** Tool definition in the registry */
export interface Tool {
  name: string;
  description: string;
  /** Parameter schema — keys are param names, values describe the param */
  params: Record<string, ParamSchema>;
  /** Async executor — receives extracted params, returns result */
  execute: (params: Record<string, unknown>) => Promise<ToolResult>;
}

export type ApprovalMode = 'auto' | 'ask_first' | 'suggest_only';

export interface ParamSchema {
  type: 'string' | 'number' | 'boolean';
  required?: boolean;
  description?: string;
}

/** Facts extracted from user input for the rules engine */
export interface InputFacts {
  raw: string;
  lower: string;
  tokens: string[];
  numbers: number[];
  has_amount_ml: number | null;
  has_duration_min: number | null;
  has_priority: 'low' | 'medium' | 'high' | null;
  has_date: string | null;

  // Keyword groups
  kw_hydration: boolean;
  kw_task: boolean;
  kw_focus: boolean;
  kw_partner: boolean;
  kw_sleep: boolean;
  kw_status: boolean;
  kw_complete: boolean;
  kw_delete: boolean;
  kw_enable: boolean;
  kw_disable: boolean;
  kw_routine: boolean;
  kw_query: boolean;
  kw_log: boolean;

  // Google integration
  kw_calendar: boolean;
  kw_email: boolean;
  kw_triage: boolean;
  kw_extract: boolean;

  // API keys
  kw_apikey: boolean;

  // Hydration reminders
  kw_schedule: boolean;
  has_time_range: { startHour: number; endHour: number } | null;
  has_goal_liters: number | null;

  // Sleep logging
  has_sleep_time: string | null;

  // Reminders
  kw_remind: boolean;
  has_reminder_text: string | null;

  // Settings
  kw_settings: boolean;

  // Recurring tasks
  has_recurrence: string | null;

  // Automation from chat
  kw_automation: boolean;

  // Webhook info
  kw_webhook: boolean;
}

/** Sleep session record */
export interface SleepSession {
  session_id: string;
  sleep_start: string;
  sleep_end: string | null;
  duration_minutes: number;
}

/** Push notification reminder */
export interface Reminder {
  reminder_id: string;
  text: string;
  trigger_at: string;
  fired: boolean;
  created_at: string;
}

/** A matched intent from the rules engine */
export interface MatchedIntent {
  tool: string;
  params: Record<string, unknown>;
  priority: number;
}

/** A step in a compound routine */
export interface RoutineStep {
  tool: string;
  params: Record<string, unknown>;
}

/** Pre-built or user-defined routine */
export interface Routine {
  id: string;
  name: string;
  triggerPhrases: string[];
  steps: RoutineStep[];
  enabled: boolean;
  createdAt: string;
}

/** Automation rule (schedule or condition-based) */
export interface AutomationRule {
  id: string;
  name: string;
  description: string;
  ruleType: 'schedule' | 'condition';
  schedule: string | null;     // cron expression for schedule type
  condition: string | null;    // JSON rules-engine condition
  actions: RoutineStep[];
  enabled: boolean;
  lastTriggered: string | null;
  createdAt: string;
}

/** Overall agent response after processing input */
export interface AgentResponse {
  input: string;
  intents: MatchedIntent[];
  results: ToolResult[];
  output: string;              // Human-readable combined output
}

// ── Agentic system types ────────────────────────────

export type GoalDomain = 'health' | 'productivity' | 'finance' | 'social';
export type GoalStatus = 'active' | 'completed' | 'paused' | 'abandoned';
export type PlanStatus = 'pending' | 'in_progress' | 'completed' | 'failed';
export type StepStatus = 'pending' | 'done' | 'skipped' | 'failed';

/** A long-term goal the user wants to achieve */
export interface Goal {
  id: string;
  title: string;
  description: string | null;
  domain: GoalDomain;
  targetValue: number | null;
  currentValue: number;
  unit: string | null;
  deadline: string | null;
  status: GoalStatus;
  createdAt: string;
  updatedAt: string;
}

/** A single step within a plan */
export interface PlanStep {
  id: string;
  tool: string;
  params: Record<string, unknown>;
  condition?: string;
  dependsOn?: string[];
  status: StepStatus;
}

/** A concrete action plan generated by agents to achieve a goal */
export interface Plan {
  id: string;
  goalId: string | null;
  title: string;
  steps: PlanStep[];
  status: PlanStatus;
  scheduledFor: string | null;
  createdAt: string;
  updatedAt: string;
}

/** Tracks what agents did and outcomes */
export interface AgentAction {
  id: string;
  agent: string;
  actionType: 'plan' | 'execute' | 'monitor' | 'reflect';
  input: string | null;
  output: string | null;
  goalId: string | null;
  planId: string | null;
  success: boolean | null;
  createdAt: string;
}

export type PatternType = 'time_habit' | 'correlation' | 'preference' | 'anomaly';

/** A behavioral pattern learned from user data */
export interface BehaviorPattern {
  id: string;
  domain: GoalDomain;
  patternType: PatternType;
  description: string;
  data: Record<string, unknown>;
  confidence: number;
  sampleCount: number;
  lastUpdated: string;
  createdAt: string;
}

/** Insight produced by a domain agent's assess() call */
export interface AgentInsight {
  domain: GoalDomain;
  priority: 'high' | 'low';
  title: string;
  body: string;
  suggestedAction?: { tool: string; params: Record<string, unknown> };
  /** Why this nudge (pattern / context) */
  coachingWhy?: string;
  /** Actionable micro-tip */
  coachingTip?: string;
}

/** Saved coaching suggestion for adoption tracking */
export interface CoachingCommitment {
  id: string;
  suggestion: string;
  reason: string | null;
  dateSuggested: string;
  dateDue: string | null;
  adopted: boolean;
  outcome: string | null;
  createdAt: string;
}

/** Queued watcher notification */
export interface WatcherNotification {
  id: string;
  domain: GoalDomain | null;
  title: string;
  body: string;
  priority: 'high' | 'low';
  suggestedAction?: { tool: string; params: Record<string, unknown> };
  read: boolean;
  createdAt: string;
}
